version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build
      - run:
          name: SSH into the instance and deploy
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$DNS 'cd /home/ubuntu/sangam && git pull origin main && cd build && rm -rf *'
            scp -r -o StrictHostKeyChecking=no build/* $USER@$DNS:/home/ubuntu/sangam/build
            

workflows:
  deploy-to-ec2:
    jobs:
      - build_and_deploy
