version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  hold:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - run:
          name: Manual Approval
          command: echo "Manual approval required"
      - run:
          name: Sleep
          command: sleep 20s  # Adjust the duration as needed
      - run:
          name: Cancel Workflow
          command: |
            curl -X POST -H "Circle-Token: $CIRCLECI_API_TOKEN" \
            -d "{\"cancel_running\": true}" \
            https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pipeline/$CIRCLE_WORKFLOW_ID/cancel

  build_and_deploy:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build
      - run:
          name: SSH into the instance and deploy
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$DNS 'cd /home/ubuntu/funds-up/funds-up-portal && cd build && rm -rf *'
            scp -r -o StrictHostKeyChecking=no build/* $USER@$DNS:/home/ubuntu/funds-up/funds-up-portal/build
            ssh -o StrictHostKeyChecking=no $USER@$DNS 'pm2 restart 0'

workflows:
  deploy-to-ec2:
    jobs:
      - hold
      - build_and_deploy:
          requires:
            - hold
