version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: |
            npm run build
            ls -la
