version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              ignore:
                - '*'

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build
