version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:20
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build:dev
      # Remove the existing deploy steps
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: |
          ssh -oStrictHostKeyChecking=no -v $USER@$DNS "\
            sudo sh -c '\
            cd /home/ubuntu && \
            rm -rf sangam/* && \
            cp -r /path/to/circleci/build/* /home/ubuntu/sangam/'"

workflows:
  deploy-to-ec2:
    jobs:
      - build_and_deploy
      - deploy:
          requires:
            - build_and_deploy

