version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build

  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run:
          name: Deploy to EC2
          command: |
            scp -r -o StrictHostKeyChecking=no ./ $USER@$DNS/home/circleci-aws/"

workflows:
  deploy-to-ec2:
    jobs:
      - build_and_deploy
      - deploy:
          requires:
            - build_and_deploy
