version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build
      - run:
          name: SSH into the instance and deploy
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$DNS 'cd /home/ubuntu/sangam && git pull origin main && cd build && rm -rf *'
            scp -r -o StrictHostKeyChecking=no build/* $USER@$DNS:/home/ubuntu/sangam/build

  manual_approval:
    docker:
      - image: cimg/base:2020.01
    steps:
      - approval/approve:
          requires:
            - build_and_deploy

workflows:
  deploy-to-ec2:
    jobs:
      - manual_approval
