version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
            sources:
              only:
                - web

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build

