version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /.*/

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Add your build and test steps here
