version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build
          command: npm run build
      - run:
          name: SSH into the instance and deploy
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$DNS 'cd /home/ubuntu/sangam && git pull origin main && cd build && rm -rf *'
            scp -r -o StrictHostKeyChecking=no build/* $USER@$DNS:/home/ubuntu/sangam/build

  # Approval job for manual control
  approve_deployment:
    type: approval
    requires:
      - build_and_deploy


workflows:
  deploy-to-ec2:
    jobs:
      - build_and_deploy
      - approve_deployment:
          # Only run after build_and_deploy succeeds
          requires:
            - build_and_deploy
